### ISSUE TITLE
FastTiger - Lack Control access of the `GoatV1Pair.sol#takeOverPool()` function.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-goat-trading-judging#19]
FastTiger

medium

# Lack Control access of the `GoatV1Pair.sol#takeOverPool()` function.

## Summary
Due to the lack of control access to the `GoatV1Pair.sol#takeOverPool()` function, an attacker can take over the pool from a trusted initilal LP and set unfavorable initial conditions to grief the pool.
## Vulnerability Detail
The `GoatV1Pair.sol#takeOverPool()` function is used to allow a team to take over a pool from a malicious actor and prevent malicious actors from griefing the pool by setting unfavorable initial conditions.
However, an arbitrary user can take over the pool due to weak access control of the `GoatV1Pair.sol#takeOverPool()` function.
As a result, an attacker can take over the pool from a trusted initilal LP and set unfavorable initial conditions to grief the pool.
## Impact
An attacker can take over the pool from a trusted initilal LP and set unfavorable initial conditions to the pool.
## Code Snippet
https://github.com/sherlock-audit/2024-03-goat-trading/blob/main/goat-trading/contracts/exchange/GoatV1Pair.sol#L452
## Tool used

Manual Review

## Recommendation
Add the following line to the `GoatV1Pair.sol#takeOverPool()` function to allow a trusted team to take over the pool.
```solidity
    function takeOverPool(GoatTypes.InitParams memory initParams) external {
+++     require(whitelisted[msg.sender], "The LP cannot take over the pool.");
        ...SNIP
    }
```

**Comment by FastTiger777** [comment]
I believe that users with malicious purposes can set unfavorable initial conditions (initialTokenMatch and bootstrapEth, virtualEth) so that tokens can be traded at a different price from other DEXs.
