### ISSUE TITLE
Solidity_ATL_Team_2 - Malicious initial liquidity provider may be able to prevent GoatV1Pair take overs

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-goat-trading-judging#37]
Solidity_ATL_Team_2

medium

# Malicious initial liquidity provider may be able to prevent GoatV1Pair take overs

## Summary
Malicious initial liquidity provider may be able to prevent pool take overs.

## Vulnerability Detail
The `takeOverPool` mechanism allows anyone who can provide 110% of the `ETH` and `token` balance a `Goatv1Pair` presale that has not reached the goal `bootstrapETH` amount after 30 days. During a take over the initial `liquidityProvider` is refunded their eth (as `WETH`) and the pair ERC-20 `token` amount they deposited. If the `token` is an ERC-777 token (`ERC777Receiver` callback) or has some type of callback that executes during token transfers a malicious initial `liquidityProvider` can force token transfers to fail causing the pool take over to fail.

[More details on `tokenReceipt` callback](https://docs.openzeppelin.com/contracts/3.x/api/token/erc777#IERC777Recipient)
## Impact
https://github.com/sherlock-audit/2024-03-goat-trading/blob/main/goat-trading/contracts/exchange/GoatV1Pair.sol#L591-L605 

```solidity
function _handleTakeoverTransfers(IERC20 weth, IERC20 token, address lp, uint256 wethAmount, uint256 tokenAmount)
        internal
    {
        if (wethAmount != 0) {
            // Malicious frontrunners can create cheaper pools buy tokens cheap
            // and make it costly for the teams to take over. So, we need to have penalty
            // for the frontrunner.
            uint256 penalty = (wethAmount * 5) / 100;
            // actual amount to transfer
            wethAmount -= penalty;
            weth.safeTransfer(lp, wethAmount);
            weth.safeTransfer(IGoatV1Factory(factory).treasury(), penalty);
        }
        token.safeTransfer(lp, tokenAmount);
    }
```
If a malicious lp can force `token.safeTransfer(lp, tokenAmount);` to always fail during a `takeOver` then they could gain permanent control on the pool.
 
## Code Snippet
https://github.com/sherlock-audit/2024-03-goat-trading/blob/main/goat-trading/contracts/exchange/GoatV1Pair.sol#L591-L605

## Tool used
Manual Review

## Recommendation
One approach to prevent this from occurring is to introduce a claiming mechanism for the initial lp to regain their tokens after a takeover. This would prevent the `takeOver` call from having to send tokens back to the lp within the same transaction.

Another approach would be to not support ERC-20 tokens that support arbitrary `onReceive()` callbacks

**Comment by Darkartt** [comment]
Escalate

I believe our reported vulnerability has been incorrectly marked as a duplicate. The key distinctions are:

*  Our Issue: Malicious LP uses token with failing transfer callbacks to sabotage a pool takeover (impact: malicious LP retains control).

*  [#69](https://github.com/sherlock-audit/2024-03-goat-trading-judging/issues/69)  Issue: Invalid pool parameters on creation prevent calculation within takeOverPool  (impact: takeover mechanism broken for the pool).

These represent different attack vectors and consequences.  Please reconsider the duplicate classification.

### Importantly, fixing the other issue would not resolve our reported vulnerability.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I believe our reported vulnerability has been incorrectly marked as a duplicate. The key distinctions are:
> 
> *  Our Issue: Malicious LP uses token with failing transfer callbacks to sabotage a pool takeover (impact: malicious LP retains control).
> 
> *  [#69](https://github.com/sherlock-audit/2024-03-goat-trading-judging/issues/69)  Issue: Invalid pool parameters on creation prevent calculation within takeOverPool  (impact: takeover mechanism broken for the pool).
> 
> These represent different attack vectors and consequences.  Please reconsider the duplicate classification.
> 
> ### Importantly, fixing the other issue would not resolve our reported vulnerability.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by zzykxx** [comment]
Escalate

Not a duplicate of #69 and should be out of scope because this issue only exists with ERC777 tokens:
> If the token is an ERC-777 token (ERC777Receiver callback) or has some type of callback that executes during token transfers a malicious initial liquidityProvider can force token transfers to fail causing the pool take over to fail

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Not a duplicate of #69 and should be out of scope because this issue only exists with ERC777 tokens:
> > If the token is an ERC-777 token (ERC777Receiver callback) or has some type of callback that executes during token transfers a malicious initial liquidityProvider can force token transfers to fail causing the pool take over to fail
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
If #52 is invalid then this issue must also be invalid. In this [comment](https://github.com/sherlock-audit/2024-03-goat-trading-judging/issues/52#issuecomment-2040104272) I wrote why I left non-standard erc20 tokens with a callback.

**Comment by Evert0x** [comment]
Planning to accept escalations and invalidate issue

**Comment by Evert0x** [comment]
Result:
Unique 
Invalid

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Darkartt](https://github.com/sherlock-audit/2024-03-goat-trading-judging/issues/37/#issuecomment-2039766109): accepted
- [zzykxx](https://github.com/sherlock-audit/2024-03-goat-trading-judging/issues/37/#issuecomment-2041353880): accepted
