### ISSUE TITLE
zzykxx - Constant `k` is calculated incorrectly when performing swaps during pre-sale

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-goat-trading-judging#64]
zzykxx

high

# Constant `k` is calculated incorrectly when performing swaps during pre-sale

## Summary

`k` is calculated incorrectly when performing swaps during pre-sale that don't turn the pair into an AMM.

## Vulnerability Detail

When swapping tokens during the pre-sale liquidity provider fees are not collected and the protocol correctly adjusts the `swapVars.finalReserveEth` variable by `swapVars.lpFeesCollected` in the [swap()](https://github.com/sherlock-audit/2024-03-goat-trading/blob/main/goat-trading/contracts/exchange/GoatV1Pair.sol#L242) function.

However when [performing a swap during pre-sale that doesn't turn the pair into an AMM](https://github.com/sherlock-audit/2024-03-goat-trading/blob/main/goat-trading/contracts/exchange/GoatV1Pair.sol#L309) the `swapVars.finalReserveEth` is not adjusted:

```solidity
if (swapVars.isPresale && ((swapVars.finalReserveEth + swapVars.lpFeesCollected) > swapVars.bootstrapEth)) {
    ...
} else {
    ...
    (swapVars.virtualEthReserveAfter, swapVars.virtualTokenReserveAfter) =
@>      _getReserves(swapVars.vestingUntil, swapVars.finalReserveEth, swapVars.finalReserveToken);

    if (
        swapVars.virtualEthReserveBefore * swapVars.virtualTokenReserveBefore
            > swapVars.virtualEthReserveAfter * swapVars.virtualTokenReserveAfter
    ) {
        revert GoatErrors.KInvariant();
    }
}
```

This leads to the constant `k` being calculated incorrectly which breaks a core invariants of AMM protocols.

## Impact

Constant `k` is calculated incorrectly when performing swaps during pre-sale that don't turn the pair into an AMM.

## Tool used

Manual Review

## Recommendation

Adjust the `swapVars.finalReserveEth` variable by `swapVars.lpFeesCollected` during pre-sale:

```solidity
if(swapVars.isPresale) {
    (swapVars.virtualEthReserveAfter, swapVars.virtualTokenReserveAfter) = _getReserves(swapVars.vestingUntil, swapVars.finalReserveEth + swapVars.lpFeesCollected, swapVars.finalReserveToken);
}else{
    (swapVars.virtualEthReserveAfter, swapVars.virtualTokenReserveAfter) = _getReserves(swapVars.vestingUntil, swapVars.finalReserveEth, swapVars.finalReserveToken);
}
```

**Comment by zzykxx** [comment]
Escalate

This has been overlooked, not a duplicate of #53.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This has been overlooked, not a duplicate of #53.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by chiranz** [comment]
Even though this is not duplicate of #53 but still not a valid issue according to us.. It is our design decision to check k without adding `lpFeesCollected` to the `finalReserveEth`. Because we don't want to give users cheap tokens by adding lpfees to check for k invariant. So, K will keep increasing in the presale phase and is desired.

**Comment by Evert0x** [comment]
Planning to accept escalation, remove duplication state, and keep issue invalid.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zzykxx](https://github.com/sherlock-audit/2024-03-goat-trading-judging/issues/64/#issuecomment-2041378476): accepted
